version: '3.1'
services:
  mysql:
    image: mysql:latest
    container_name: vendas-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vendas
      MYSQL_USER: vendas
      MYSQL_PASSWORD: vendas
    ports:
      - "3306:3306"
    restart: unless-stopped
  vendas-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    container_name: vendas-api
    restart: unless-stopped

